# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170830_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='imageUrl',
            field=models.URLField(default='http://i.imgur.com/DtJyTkB.jpg'),
        ),
    ]
